site_name: vcchusky
theme:
    name: 'material'
pages:
    - Home: index.md
    - Intelligence: cortex.md
    - Navigation: navigation.md
    - Control: control.md
    - PointCloudProcessing: pcprocessing.md

