// Generated by gencpp from file husky_cortex/meshmap.msg
// DO NOT EDIT!


#ifndef HUSKY_CORTEX_MESSAGE_MESHMAP_H
#define HUSKY_CORTEX_MESSAGE_MESHMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace husky_cortex
{
template <class ContainerAllocator>
struct meshmap_
{
  typedef meshmap_<ContainerAllocator> Type;

  meshmap_()
    : header()
    , V()
    , F()
    , reebi()
    , vtype()  {
    }
  meshmap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , V(_alloc)
    , F(_alloc)
    , reebi(_alloc)
    , vtype(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _V_type;
  _V_type V;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _F_type;
  _F_type F;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _reebi_type;
  _reebi_type reebi;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _vtype_type;
  _vtype_type vtype;




  typedef boost::shared_ptr< ::husky_cortex::meshmap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_cortex::meshmap_<ContainerAllocator> const> ConstPtr;

}; // struct meshmap_

typedef ::husky_cortex::meshmap_<std::allocator<void> > meshmap;

typedef boost::shared_ptr< ::husky_cortex::meshmap > meshmapPtr;
typedef boost::shared_ptr< ::husky_cortex::meshmap const> meshmapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_cortex::meshmap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_cortex::meshmap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace husky_cortex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'husky_cortex': ['/home/husky/husky/husky_ws/src/husky_cortex/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::husky_cortex::meshmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_cortex::meshmap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_cortex::meshmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_cortex::meshmap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_cortex::meshmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_cortex::meshmap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_cortex::meshmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7166ceb0ee7397fa9f91bd03faa01c8";
  }

  static const char* value(const ::husky_cortex::meshmap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7166ceb0ee7397fULL;
  static const uint64_t static_value2 = 0xa9f91bd03faa01c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_cortex::meshmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_cortex/meshmap";
  }

  static const char* value(const ::husky_cortex::meshmap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_cortex::meshmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point[] V\n\
int32[] F\n\
int32[] reebi\n\
int32[] vtype\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::husky_cortex::meshmap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_cortex::meshmap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.V);
      stream.next(m.F);
      stream.next(m.reebi);
      stream.next(m.vtype);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct meshmap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_cortex::meshmap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_cortex::meshmap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "V[]" << std::endl;
    for (size_t i = 0; i < v.V.size(); ++i)
    {
      s << indent << "  V[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.V[i]);
    }
    s << indent << "F[]" << std::endl;
    for (size_t i = 0; i < v.F.size(); ++i)
    {
      s << indent << "  F[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.F[i]);
    }
    s << indent << "reebi[]" << std::endl;
    for (size_t i = 0; i < v.reebi.size(); ++i)
    {
      s << indent << "  reebi[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.reebi[i]);
    }
    s << indent << "vtype[]" << std::endl;
    for (size_t i = 0; i < v.vtype.size(); ++i)
    {
      s << indent << "  vtype[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.vtype[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_CORTEX_MESSAGE_MESHMAP_H
