// Generated by gencpp from file husky_cortex/reebgraph.msg
// DO NOT EDIT!


#ifndef HUSKY_CORTEX_MESSAGE_REEBGRAPH_H
#define HUSKY_CORTEX_MESSAGE_REEBGRAPH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <husky_cortex/adjlist.h>

namespace husky_cortex
{
template <class ContainerAllocator>
struct reebgraph_
{
  typedef reebgraph_<ContainerAllocator> Type;

  reebgraph_()
    : header()
    , graph()
    , vtype()
    , etype()  {
    }
  reebgraph_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , graph(_alloc)
    , vtype(_alloc)
    , etype(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::husky_cortex::adjlist_<ContainerAllocator>  _graph_type;
  _graph_type graph;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _vtype_type;
  _vtype_type vtype;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _etype_type;
  _etype_type etype;




  typedef boost::shared_ptr< ::husky_cortex::reebgraph_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_cortex::reebgraph_<ContainerAllocator> const> ConstPtr;

}; // struct reebgraph_

typedef ::husky_cortex::reebgraph_<std::allocator<void> > reebgraph;

typedef boost::shared_ptr< ::husky_cortex::reebgraph > reebgraphPtr;
typedef boost::shared_ptr< ::husky_cortex::reebgraph const> reebgraphConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_cortex::reebgraph_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_cortex::reebgraph_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace husky_cortex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'husky_cortex': ['/home/husky/husky/husky_ws/src/husky_cortex/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::husky_cortex::reebgraph_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_cortex::reebgraph_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_cortex::reebgraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_cortex::reebgraph_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_cortex::reebgraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_cortex::reebgraph_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_cortex::reebgraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c75f76d5bc8878e91eeeefcac312eab2";
  }

  static const char* value(const ::husky_cortex::reebgraph_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc75f76d5bc8878e9ULL;
  static const uint64_t static_value2 = 0x1eeeefcac312eab2ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_cortex::reebgraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_cortex/reebgraph";
  }

  static const char* value(const ::husky_cortex::reebgraph_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_cortex::reebgraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
adjlist graph\n\
int32[] vtype\n\
int32[] etype\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: husky_cortex/adjlist\n\
adjedgelist[] graph\n\
\n\
================================================================================\n\
MSG: husky_cortex/adjedgelist\n\
adjedge[] edgelist\n\
\n\
================================================================================\n\
MSG: husky_cortex/adjedge\n\
int32 from\n\
int32 to\n\
float64 cost = 1.\n\
";
  }

  static const char* value(const ::husky_cortex::reebgraph_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_cortex::reebgraph_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.graph);
      stream.next(m.vtype);
      stream.next(m.etype);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reebgraph_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_cortex::reebgraph_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_cortex::reebgraph_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "graph: ";
    s << std::endl;
    Printer< ::husky_cortex::adjlist_<ContainerAllocator> >::stream(s, indent + "  ", v.graph);
    s << indent << "vtype[]" << std::endl;
    for (size_t i = 0; i < v.vtype.size(); ++i)
    {
      s << indent << "  vtype[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.vtype[i]);
    }
    s << indent << "etype[]" << std::endl;
    for (size_t i = 0; i < v.etype.size(); ++i)
    {
      s << indent << "  etype[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.etype[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_CORTEX_MESSAGE_REEBGRAPH_H
